package CapableSimulator.Actors.Animals.Predators;


import CapableSimulator.Utils.CapableEnums;
import CapableSimulator.Utils.PathFinder;
import CapableSimulator.Utils.SpawningAgent;
import CapableSimulator.Utils.TileFinder;
import itumulator.executable.DisplayInformation;
import itumulator.world.Location;
import itumulator.world.World;

import java.awt.*;
import java.util.*;
import java.util.List;

public class Bear extends Predator {

    /** The center location of the bear's territory.
     *  The bear will only move around within the territory, except if it findes food just outside its territory.
     * */
    private Location territoryCenter;

    /** The size of the bear's territory, given as a radius from the center location.
     * */
    private int territoryRadius;

    private static final List<String> fightPriority = new ArrayList<>();
    static {
        fightPriority.add("wolf");
        fightPriority.add("bear");
        fightPriority.add("putin");
        //fightPriority.add("beartin");
    }

    private static final EnumMap<CapableEnums.AnimalSize, Double> strengthBonus_AnimalSize = new EnumMap<>(CapableEnums.AnimalSize.class);
    static {
        strengthBonus_AnimalSize.put(CapableEnums.AnimalSize.BABY, 8.0);
        strengthBonus_AnimalSize.put(CapableEnums.AnimalSize.ADULT, 5.0);
    }
    private static final EnumMap<CapableEnums.FungiState, Double> strengthBonus_FungiState = new EnumMap<>(CapableEnums.FungiState.class);
    static {
        strengthBonus_FungiState.put(CapableEnums.FungiState.NORMAL, 0.0);
        strengthBonus_FungiState.put(CapableEnums.FungiState.FUNGI, -2.0);
    }

    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        displayInformations.put("Small-Normal-Awake", new DisplayInformation(Color.BLACK, "bear-small"));                   // The display information of a small awake normal bear
        displayInformations.put("Big-Normal-Awake", new DisplayInformation(Color.BLACK, "bear"));                           // The display information of a big awake normal bear

        displayInformations.put("Small-Normal-Sleeping", new DisplayInformation(Color.BLACK, "bear-small-sleeping"));       // The display information of a small sleeping normal bear
        displayInformations.put("Big-Normal-Sleeping", new DisplayInformation(Color.BLACK, "bear-sleeping"));               // The display information of a big sleeping normal bear

        displayInformations.put("Small-Fungi-Awake", new DisplayInformation(Color.BLACK, "bear-fungi-small"));              // The display information of a small awake fungus bear
        displayInformations.put("Big-Fungi-Awake", new DisplayInformation(Color.BLACK, "bear-fungi"));                      // The display information of a big awake fungus bear

        displayInformations.put("Small-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "bear-fungi-small-sleeping"));  // The display information of a small sleeping fungus bear
        displayInformations.put("Big-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "bear-fungi-sleeping"));          // The display information of a big sleeping fungus bear
    }


    /* ----- ----- ----- ----- Constructors ----- ----- ----- ----- */

    public Bear(World world) {
        super("bear", world, 40, 0, 35);
        this.territoryCenter = new Location(0, 0);
        this.territoryRadius = 2;
    }

    public Bear(World world, Location territoryCenter) {
        super("bear", world, 40, 0, 35);
        this.territoryCenter = territoryCenter;
        this.territoryRadius = 2;
    }

    public Bear(World world, int age, int MATING_AGE, int MATING_COOLDOWN_DURATION,  Location territoryCenter) {
        super("bear", world, 40, age, 35, MATING_AGE, MATING_COOLDOWN_DURATION);
        this.territoryCenter = territoryCenter;
        this.territoryRadius = 2;
    }

    /* ----- ----- ----- ----- Behavior ----- ----- ----- ----- */

    @Override
    public void act(World world) {
        super.act(world);
        if (isDead()) return;

        if(isInfected()) {
            fungiSpore.act(world);
        }
        else if (world.isDay()) {
            if (isOnMap()){
                if (getAnimalSize().equals(CapableEnums.AnimalSize.ADULT)) {
                    if (!(tryMate() || tryFight() || lookForFood(1)))
                        move();
                }
                else {
                    if (!lookForFood(2))
                        move();
                }
            }
        }
    }

    @Override
    public void move(){
        Set<Location> territory = world.getSurroundingTiles(territoryCenter, territoryRadius- 1);
        Set<Location> neighbours = world.getEmptySurroundingTiles(getLocation());

        List<Location> validNeighbours = new ArrayList<>();
        for (Location neighbour : neighbours) {
            if (PathFinder.distance(getTerritoryCenter(), neighbour) <= territoryRadius) {
                if (world.isTileEmpty(neighbour)) validNeighbours.add(neighbour);
            }

        }
        Location searchLocation;
        if (validNeighbours.isEmpty()) {
            Location nearestLocation = PathFinder.getClosestTile(world, getLocation(), territoryCenter);
            if (nearestLocation == null) return;
            searchLocation = nearestLocation;
        }
        else {
            Random rand = new Random();
            searchLocation = validNeighbours.get(rand.nextInt(validNeighbours.size()));
        }
        world.move(this, searchLocation);
    }
    // TODO make test that test if a bear moves out of it territory.

    @Override
    public void updateOnMap(Location location, boolean isOnMap) {
        super.updateOnMap(location, isOnMap);
        territoryCenter = location;
    }

    /* ----- ----- ----- ----- Fighting ----- ----- ----- ----- */

    @Override
    protected boolean isAnimalEnemy(Predator possibleEnemy) {
        if (possibleEnemy instanceof Wolf wolf) {
            List<Wolf> nearbyWolfs = new ArrayList<>();
            wolf.getWolfGang().getNearbyWolfsFromGang(wolf,  nearbyWolfs);
            return nearbyWolfs.size() < 3;
        }
        else if (possibleEnemy instanceof Bear){
            return !canMate();
        }
        return false;
    }

    @Override
    public double getStrengthValue() {
        double strength = 0;
        strength += strengthBonus_AnimalSize.get(getAnimalSize());
        strength += strengthBonus_FungiState.get(getFungiState());
        return strength;
    }

    /* ----- ----- ----- ----- Reproduction ----- ----- ----- ----- */

    /** Tries to find a mate, and produce an offspring.
     * @return Returns true if a mate is found and a successful reproduction occurs or a mate is found and the bear goes towards it.
     * Otherwise, returns false.
     */
    private boolean tryMate() {
        List<Bear> mates = new ArrayList<>();

        if (!lookForMate(mates, 4)) return false;

        Bear mate = mates.get(new  Random().nextInt(mates.size()));
        Location mateLocation = mate.getLocation();

        if (moveNextToTarget(mateLocation))
            mate(mate);
        return true;
    }

    /** Tries to find mates within a certain area.
     * @param mates is the list wherein the found mates are inserted into.
     * @param radius The radius of the area to search for mates in.
     * @return Returns true if any possible mates were found, otherwise returns false.
     */
    private boolean lookForMate(List<Bear> mates, int radius) {
        Set<Location> neighbors = world.getSurroundingTiles(getLocation(), radius);
        for (Location l : neighbors) {
            Object o = world.getTile(l);
            if (o instanceof Bear bear) {
                if (bear.canMate())
                    mates.add(bear);
            }
        }
        return !mates.isEmpty();
    }

    /** Produces a bear offspring and adds it to the world.
     * @param bear The actor to mate with.
     */
    private void mate(Bear bear) {
        System.out.println("Bear mate");

        Location offspringLocation = TileFinder.getEmptyTileAroundActor(world, this, true);
        Location offspringTerritoryLocation = TileFinder.getEmptyTile(world, true);
        if (offspringLocation == null) return;

        // makes new rabbit
        Bear offspring = new Bear(world, offspringLocation);

        // Spawn offspring at location
        SpawningAgent.spawnActorAtLocation(world, offspring,  offspringTerritoryLocation);

        // Updates the relevant mating information.
        animalJustReproduce();
        bear.animalJustReproduce();
    }

    /* ----- ----- ----- ----- Events ----- ----- ----- ----- */

    @Override
    public void onDawn() {
        setAnimalState(CapableEnums.AnimalState.AWAKE);
    }

    @Override
    public void onNightFall() {
        setAnimalState(CapableEnums.AnimalState.SLEEPING);
    }

    @Override
    public void onDusk() {

    }

    /* ----- ----- ----- ----- Getters and Setters ----- ----- ----- ----- */

    @Override
    public DisplayInformation getInformation() {

        DisplayInformation returnValue = displayInformations.get(getDisplayInformationsKey());

        return returnValue;
    }

    /** Retrieves the center location of the bear's territory.
     * @return Returns the center location of the bear's territory.
     */
    public Location getTerritoryCenter() { return territoryCenter; }

    /** Retrieves the radius of the bear's territory.
     * @return Returns the radius of the bear's territory, the radius is from the center location.
     */
    public int getTerritoryRadius() { return territoryRadius; }
}
