package CapableSimulator.Actors.Animals.Predators;

import CapableSimulator.Actors.Animals.Animal;
import CapableSimulator.CapableWorld;
import itumulator.executable.DisplayInformation;
import itumulator.world.World;

import java.awt.*;
import java.util.HashMap;
import java.util.Map;


public class Putin extends Animal {

    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        // TODO Fix all the different possible Putin dispay informations
        displayInformations.put("Small-Normal-Awake", new DisplayInformation(Color.BLACK, "wolf-small"));                   // The display information of a small awake normal putin
        displayInformations.put("Big-Normal-Awake", new DisplayInformation(Color.BLACK, "wolf"));                           // The display information of a big awake normal putin

        displayInformations.put("Small-Normal-Sleeping", new DisplayInformation(Color.BLACK, "wolf-small-sleeping"));       // The display information of a small sleeping normal putin
        displayInformations.put("Big-Normal-Sleeping", new DisplayInformation(Color.BLACK, "wolf-sleeping"));               // The display information of a big sleeping normal putin

        displayInformations.put("Small-Fungi-Awake", new DisplayInformation(Color.BLACK, "wolf-fungi-small"));              // The display information of a small awake fungus putin
        displayInformations.put("Big-Fungi-Awake", new DisplayInformation(Color.BLACK, "wolf-fungi"));                      // The display information of a big awake fungus putin

        displayInformations.put("Small-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "wolf-fungi-small-sleeping"));  // The display information of a small sleeping fungus putin
        displayInformations.put("Big-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "wolf-fungi-sleeping"));          // The display information of a big sleeping fungus putin
    }

    DisplayInformation diPutin = new DisplayInformation(Color.blue, "putin");

    public Putin(CapableWorld world){
        super("putin", world, 50, 0,100);
        /*this.energy = 100;
        this.MAX_ENERGY = 1000;
        this.age = 73;*/
    }


    /* ----- ----- ----- ----- Behavior ----- ----- ----- ----- */

    @Override
    public void act(World world){
        lookForFood(5);
    }

    @Override
    protected void doEverySimulationStep() {}

    /* ----- ----- ----- ----- Events ----- ----- ----- ----- */

    @Override
    public void onDawn(){

    }

    @Override
    public void onNightFall(){

    }

    @Override
    public void onDusk() {

    }

    /* ----- ----- ----- Getters and Setters ----- ----- ----- */

    @Override
    public DisplayInformation getInformation() { return diPutin; }

}

