package CapableSimulator.Actors.Animals.Predators;

import CapableSimulator.Actors.Carcass;

import CapableSimulator.Actors.Fungis.Fungus;
import CapableSimulator.Actors.WorldActor;
import CapableSimulator.Utils.CapableEnums;
import CapableSimulator.Utils.PathFinder;
import CapableSimulator.Utils.SpawningAgent;
import CapableSimulator.Utils.WorldUtils;
import itumulator.executable.DisplayInformation;
import itumulator.world.Location;
import itumulator.world.World;

import java.awt.*;
import java.util.*;
import java.util.List;


public class Putin extends Predator {

    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        // TODO Fix all the different possible Putin dispay informations
        displayInformations.put("Normal-Awake", new DisplayInformation(Color.BLACK, "putin"));                  // The display information of a small awake normal putin
        displayInformations.put("Normal-Sleeping-0", new DisplayInformation(Color.BLACK, "putin-sleeping1"));   // The display information of a big sleeping normal putin
        displayInformations.put("Normal-Sleeping-1", new DisplayInformation(Color.BLACK, "putin-sleeping2"));   // The display information of a big sleeping normal putin
        displayInformations.put("Fungi-Awake", new DisplayInformation(Color.BLACK, "putin-fungi"));                   // The display information of a big awake fungus putin
        displayInformations.put("Fungi-Sleeping-0", new DisplayInformation(Color.BLACK, "putin-fungi-sleeping1"));    // The display information of a big sleeping normal putin
        displayInformations.put("Fungi-Sleeping-1", new DisplayInformation(Color.BLACK, "putin-fungi-sleeping2"));    // The display information of a big sleeping normal putin
    }

    /** Default constructor.
     * @param world The world wherein the actor exists.
     */
    public Putin(World world){
        super("putin", world, 50, 0,100);

        setupPredatorStrength(5, 3, 5);
    }

    /* ----- ----- ----- ----- Behavior ----- ----- ----- ----- */

    @Override
    public void act(World world){
        super.act(world);
        if (isDead()) return;

        if(isInfected()) {

        }
        else if (world.isDay()) {
            if (lookForShrooms() instanceof Fungus fungus) {
                if (moveNextToTarget(fungus.getLocation()))
                    eat(fungus);
            }
            else if (isOnMap() && getAnimalSize().equals(CapableEnums.AnimalSize.ADULT)) {
                if (!(tryFight() || lookForFood(1))) {
                    move();
                }
            }
            else if (isOnMap()) {
                if (!(lookForFood(1))) {
                    move();
                }
            }
        }
    }

    /**
     * @return Returns a reference to the nearest fungus on the world map, if there is no fungus' on the map returns null.
     */
    private WorldActor lookForShrooms() {
        List<Fungus> fungusList = new ArrayList<>();
        for (Object o : WorldUtils.getAllObjectOnWorldMap(world)) {
            if (o instanceof Fungus fungus)
                fungusList.add(fungus);
        }
        return WorldUtils.getNearestActor(world,this, fungusList);
    }

    @Override
    protected void eat(WorldActor actor) {
        if (actor instanceof Fungus)
            becomeInfected();

        super.eat(actor);
    }

    @Override
    public Carcass die() {
        Location location = getLocation();
        PutinEgg egg = new PutinEgg(world);

        if (isInfected()) {
            spreadSpores(world);
            world.delete(this);
        }
        updateOnMap(null, false);
        SpawningAgent.spawnActorAtLocation(world, egg, location);
        setDead();

        return null;
    }

    /* ----- ----- ----- ----- Fighting ----- ----- ----- ----- */

    @Override
    protected void attackEnemy(Predator enemyActor) {
        if (enemyActor instanceof Bear bear) {
            tryMountBear(bear);
        }
        else {
            super.attackEnemy(enemyActor);
        }
    }

    @Override
    protected boolean isAnimalEnemy(Predator possibleEnemy) {
        switch (possibleEnemy) {
            case Wolf wolf -> {
                List<Wolf> nearbyWolfs = new ArrayList<>();
                wolf.getWolfGang().getNearbyWolfsFromGang(wolf,  nearbyWolfs);
                return nearbyWolfs.size() < 4;
            }
            case Bear bear -> { return true; }
            case Putin putin -> { return true; }
            default -> {
                return false;
            }
        }

    }

    /* ----- ----- ----- ----- Bertin ----- ----- ----- ----- */

    /**
     * @param bear The bear putin will try to mount.
     * @throws NullPointerException Throws exception if bear is null.
     */
    private void tryMountBear(Bear bear) {
        if (bear == null)
            throw  new NullPointerException("bear is null");

        double winChance = getWinChance(bear);
        System.out.println("Putin trying to mount bear, with a win chance of: " + (winChance * 100.0) + "%");
        if (new Random().nextDouble() < winChance) {
            mountBear(bear);
        }
        else {
            die();
        }
    }

    /**
     * @param bear The bear to mount.
     * @throws NullPointerException Throws exception if bear is null.
     */
    private void mountBear(Bear bear) {
        if (bear == null)
            throw  new NullPointerException("bear is null");

        Location beartinLocation = PathFinder.getEmptyTileAroundLocation(world, getLocation(), 1);
        Beartin beartin = new Beartin(world, 100, getAge(), 100);

        if (bear.isInfected() || isInfected())
            beartin.becomeInfected();

        world.delete(bear);
        world.delete(this);

        SpawningAgent.spawnActorAtLocation(world, beartin,  beartinLocation);
    }

    /* ----- ----- ----- Getters and Setters ----- ----- ----- */

    @Override
    public DisplayInformation getInformation() {
        return displayInformations.get(getDisplayInformationsKey());
    }

    @Override
    protected String getDisplayInformationsKey() {
        //String key = fungiState.label + "-" + animalState.label + "-" + (world.getCurrentTime() % 2);
        String key;
        if (getAnimalState().equals(CapableEnums.AnimalState.SLEEPING))
            key = getFungiState().label + "-" + getAnimalState().label + "-" + (world.getCurrentTime() % 2);
        else
            key = getFungiState().label + "-" + getAnimalState().label;

        return key;
    }
}

