package CapableSimulator.Actors.Animals.Predators;

import CapableSimulator.Actors.Animals.Animal;
import CapableSimulator.CapableWorld;
import CapableSimulator.Utils.CapableEnums;
import CapableSimulator.Utils.PathFinder;
import CapableSimulator.Utils.SpawningAgent;
import itumulator.executable.DisplayInformation;
import itumulator.world.Location;
import itumulator.world.World;

import java.awt.*;
import java.util.*;
import java.util.List;


public class Putin extends Predator {

    private static final EnumMap<CapableEnums.AnimalSize, Double> strengthBonus_AnimalSize = new EnumMap<>(CapableEnums.AnimalSize.class);
    static {
        strengthBonus_AnimalSize.put(CapableEnums.AnimalSize.BABY, 6.0);
        strengthBonus_AnimalSize.put(CapableEnums.AnimalSize.ADULT, 10.0);
    }
    private static final EnumMap<CapableEnums.FungiState, Double> strengthBonus_FungiState = new EnumMap<>(CapableEnums.FungiState.class);
    static {
        strengthBonus_FungiState.put(CapableEnums.FungiState.NORMAL, 0.0);
        strengthBonus_FungiState.put(CapableEnums.FungiState.FUNGI, 5.0);
    }

    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        // TODO Fix all the different possible Putin dispay informations
        displayInformations.put("Small-Normal-Awake", new DisplayInformation(Color.BLACK, "wolf-small"));                   // The display information of a small awake normal putin
        displayInformations.put("Big-Normal-Awake", new DisplayInformation(Color.BLACK, "wolf"));                           // The display information of a big awake normal putin

        displayInformations.put("Small-Normal-Sleeping", new DisplayInformation(Color.BLACK, "wolf-small-sleeping"));       // The display information of a small sleeping normal putin
        displayInformations.put("Big-Normal-Sleeping", new DisplayInformation(Color.BLACK, "wolf-sleeping"));               // The display information of a big sleeping normal putin

        displayInformations.put("Small-Fungi-Awake", new DisplayInformation(Color.BLACK, "wolf-fungi-small"));              // The display information of a small awake fungus putin
        displayInformations.put("Big-Fungi-Awake", new DisplayInformation(Color.BLACK, "wolf-fungi"));                      // The display information of a big awake fungus putin

        displayInformations.put("Small-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "wolf-fungi-small-sleeping"));  // The display information of a small sleeping fungus putin
        displayInformations.put("Big-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "wolf-fungi-sleeping"));          // The display information of a big sleeping fungus putin
    }

    DisplayInformation diPutin = new DisplayInformation(Color.blue, "putin");
    static DisplayInformation diPutinSleeping0 = new DisplayInformation(Color.blue, "putin-sleeping1");
    static DisplayInformation diPutinSleeping1 = new DisplayInformation(Color.blue, "putin-sleeping2");
    private static final List<DisplayInformation> sleepingAnimations = new ArrayList<>();
    static {
        sleepingAnimations.add(diPutinSleeping0);
        sleepingAnimations.add(diPutinSleeping1);
    }

    public Putin(CapableWorld world){
        super("putin", world, 50, 0,100);

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
    }

    @Override
    public double getStrengthValue() {
        double strength = 0;
        strength += strengthBonus_AnimalSize.get(animalSize);
        strength += strengthBonus_FungiState.get(fungiState);
        return strength;
    }

    @Override
    protected boolean isAnimalEnemy(Predator possibleEnemy) {
        switch (possibleEnemy) {
            case Wolf wolf -> {
                List<Wolf> nearbyWolfs = new ArrayList<>();
                wolf.getWolfGang().getNearbyWolfsFromGang(wolf,  nearbyWolfs);
                return nearbyWolfs.size() < 4;
            }
            case Bear bear -> { return true; }
            case Putin putin -> { return true; }
            default -> {
                return false;
            }
        }

    }


    /* ----- ----- ----- ----- Behavior ----- ----- ----- ----- */
//TODO make beartin
    @Override
    public void act(World world){
        super.act(world);
        if (isDead()) return;

        if(isInfected()) {

        }
        else if (world.isDay()) {
            if (isOnMap() && animalSize.equals(CapableEnums.AnimalSize.ADULT)) {
                if (!(tryFight() || lookForFood(1))) {
                    move();
                }
            }
            else if (isOnMap()) {
                if (!(lookForFood(1))) {
                    move();
                }
            }
        }

    }

    @Override
    protected void doEverySimulationStep() {}




    /* ----- ----- ----- ----- Fighting ----- ----- ----- ----- */

    @Override
    protected boolean tryFight() {
        return super.tryFight();
    }

    @Override
    protected void attackEnemy(Predator enemyActor) {
        if (enemyActor instanceof Bear bear) {
            tryMountBear(bear);
        }
        else {
            super.attackEnemy(enemyActor);
        }
    }

    private void tryMountBear(Bear bear) {
        double winChance = getWinChance(bear);
        System.out.println("Putin trying to mount bear, with a win chance of: " + (winChance * 100.0) + "%");
        if (new Random().nextDouble() < winChance) {
            mountBear(bear);
        }
        else {
            die();
        }
    }

    private void mountBear(Bear bear) {
        Location beartinLocation = PathFinder.getEmptyTileAroundLocation(world, getLocation(), 1);
        Beartin beartin = new Beartin(world, 100, getAge(), 100);

        if (bear.isInfected() || isInfected())
            beartin.becomeInfected();

        world.delete(bear);
        world.delete(this);

        new SpawningAgent(world).spawnActorAtLocation(beartin,  beartinLocation);
    }

    /* ----- ----- ----- ----- Events ----- ----- ----- ----- */

    @Override
    public void onDawn(){
        animalState = CapableEnums.AnimalState.AWAKE;
    }

    @Override
    public void onNightFall(){
        animalState = CapableEnums.AnimalState.SLEEPING;
    }

    @Override
    public void onDusk() {





    }

    /* ----- ----- ----- Getters and Setters ----- ----- ----- */

    @Override
    public DisplayInformation getInformation() {

        if (world.isDay())
            return diPutin;
        else {
            return sleepingAnimations.get(world.getCurrentTime() % 2);
        }
    }




}

