package CapableSimulator.Actors.Animals.Predators;

import CapableSimulator.Actors.Animals.Animal;
import CapableSimulator.Actors.Animals.AnimalFlock;
import CapableSimulator.Actors.Animals.FlockAnimal;
import CapableSimulator.Actors.Carcass;
import CapableSimulator.Actors.Shelter.AnimalShelter;
import CapableSimulator.Actors.Shelter.WolfDen;
import CapableSimulator.Actors.WorldActor;
import CapableSimulator.CapableWorld;
import CapableSimulator.Utils.*;
import itumulator.executable.DisplayInformation;
import itumulator.world.Location;
import itumulator.world.World;

import java.awt.*;
import java.util.*;
import java.util.List;

public class Wolf extends Predator implements FlockAnimal {

    //the pack that the wolf is part of
    //Set<Actor> wolfGang;
    protected WolfGang wolfGang;

    protected Wolf alpha;
    protected WolfDen wolfDen;

    protected CapableEnums.WolfType wolfType;

    private static final EnumMap<CapableEnums.AnimalSize, Double> strengthBonus_AnimalSize = new EnumMap<>(CapableEnums.AnimalSize.class);
    static {
        strengthBonus_AnimalSize.put(CapableEnums.AnimalSize.BABY, 4.0);
        strengthBonus_AnimalSize.put(CapableEnums.AnimalSize.ADULT, 7.0);
    }
    private static final EnumMap<CapableEnums.FungiState, Double> strengthBonus_FungiState = new EnumMap<>(CapableEnums.FungiState.class);
    static {
        strengthBonus_FungiState.put(CapableEnums.FungiState.NORMAL, 0.0);
        strengthBonus_FungiState.put(CapableEnums.FungiState.FUNGI, -2.0);
    }
    private static final EnumMap<CapableEnums.WolfType, Double> strengthBonus_WolfType = new EnumMap<>(CapableEnums.WolfType.class);
    static {
        strengthBonus_WolfType.put(CapableEnums.WolfType.NPC, 0.0);
        strengthBonus_WolfType.put(CapableEnums.WolfType.ALPHA, 5.0);
    }

    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        displayInformations.put("Small-Normal-Awake-Npc", new DisplayInformation(Color.pink, "wolf-small"));                        // The display information of a small awake normal wolf
        displayInformations.put("Big-Normal-Awake-Npc", new DisplayInformation(Color.magenta, "wolf"));                             // The display information of a big awake normal wolf

        displayInformations.put("Small-Normal-Sleeping-Npc", new DisplayInformation(Color.pink, "wolf-small-sleeping"));            // The display information of a small sleeping normal wolf
        displayInformations.put("Big-Normal-Sleeping-Npc", new DisplayInformation(Color.magenta, "wolf-sleeping"));                 // The display information of a big sleeping normal wolf

        displayInformations.put("Small-Fungi-Awake-Npc", new DisplayInformation(Color.pink, "wolf-fungi-small"));                   // The display information of a small awake fungus wolf
        displayInformations.put("Big-Fungi-Awake-Npc", new DisplayInformation(Color.magenta, "wolf-fungi"));                        // The display information of a big awake fungus wolf

        displayInformations.put("Small-Fungi-Sleeping-Npc", new DisplayInformation(Color.pink, "wolf-fungi-small-sleeping"));       // The display information of a small sleeping fungus wolf
        displayInformations.put("Big-Fungi-Sleeping-Npc", new DisplayInformation(Color.magenta, "wolf-fungi-sleeping"));            // The display information of a big sleeping fungus wolf

        // Alpha
        displayInformations.put("Small-Normal-Awake-Alpha", new DisplayInformation(Color.pink, "alpha-wolf"));                        // The display information of a small awake normal wolf
        displayInformations.put("Big-Normal-Awake-Alpha", new DisplayInformation(Color.magenta, "alpha-wolf"));                             // The display information of a big awake normal wolf

        displayInformations.put("Small-Normal-Sleeping-Alpha", new DisplayInformation(Color.pink, "alpha-wolf-sleeping"));            // The display information of a small sleeping normal wolf
        displayInformations.put("Big-Normal-Sleeping-Alpha", new DisplayInformation(Color.magenta, "alpha-wolf-sleeping"));                 // The display information of a big sleeping normal wolf

        displayInformations.put("Small-Fungi-Awake-Alpha", new DisplayInformation(Color.pink, "alpha-wolf-fungi"));                   // The display information of a small awake fungus wolf
        displayInformations.put("Big-Fungi-Awake-Alpha", new DisplayInformation(Color.magenta, "alpha-wolf-fungi"));                        // The display information of a big awake fungus wolf

        displayInformations.put("Small-Fungi-Sleeping-Alpha", new DisplayInformation(Color.pink, "alpha-wolf-fungi-sleeping"));       // The display information of a small sleeping fungus wolf
        displayInformations.put("Big-Fungi-Sleeping-Alpha", new DisplayInformation(Color.magenta, "alpha-wolf-fungi-sleeping"));            // The display information of a big sleeping fungus wolf
    }

    /* ----- ----- ----- ----- Constructors ----- ----- ----- ----- */

    //Default constructor for wolf, used in the actorConstructorRegistry
    public Wolf(CapableWorld world) {
        super("wolf",  world, 25, 0, 30);

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;

        wolfType = CapableEnums.WolfType.NPC;

        wolfGang = null;
    }

    public Wolf(CapableWorld world, int age, int MATING_AGE, int MATING_COOLDOWN_DURATION) {
        super("wolf", world, 30, age, 30, MATING_AGE, MATING_COOLDOWN_DURATION);

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;

        wolfType = CapableEnums.WolfType.NPC;
    }

    public Wolf(CapableWorld world, WolfGang wolfgang, Wolf alpha, WolfDen wolfDen, CapableEnums.AnimalSize animalSize, CapableEnums.AnimalState animalState, CapableEnums.FungiState fungiState) {
        super("wolf", world, 30, 0, 30);

        this.wolfGang = wolfgang;
        this.alpha = alpha;
        this.wolfDen = wolfDen;

        this.animalSize = animalSize;
        this.animalState = animalState;
        this.fungiState = fungiState;

        wolfType = CapableEnums.WolfType.NPC;
    }


    /* ----- ----- ----- ----- Behavior ----- ----- ----- ----- */

    //Act method implemented from Actor, every step the wolf is updated and methods are called.
    @Override
    public void act(World world){
        super.act(world);
        if (isDead()) return;

        if(isInfected()) {

        }
        else if (wolfGang != null) {
            flockWolfBehavior();
        }
        else {
            loneWolfBehavior();
        }


    }

    private void loneWolfBehavior() {

        if (world.isDay()) {    // It's day
            if (isOnMap()){   // It's day, and it is on the map
                if (animalSize.equals(CapableEnums.AnimalSize.ADULT)) {
                    if (!(tryFight() || lookForFood(1)))
                        move();
                }
                else {
                    if (!lookForFood(2))
                        move();
                }
            }
            else {  // It's day, and it isn't on the map
                exitDen();
            }
        }
        else {  // It's night
            if (isOnMap()) {  // It's night, and it is on the map
                tryEnterDen();
            }
            else {  // It's night, and it isn't on the map

            }
        }
    }

    private void flockWolfBehavior() {

        if (world.isDay()) {
            if (isOnMap()){   // It's day and it is on the map
                if (wolfType == CapableEnums.WolfType.ALPHA) {
                    if (animalSize.equals(CapableEnums.AnimalSize.ADULT)) {
                        if (!(tryFight() || lookForFood(1)))
                            move();
                    }
                    else {
                        if (!lookForFood(2))
                            move();
                    }

                    if (isDead())
                        return;
                    wolfGang.alphaMoved(world.getLocation(this));
                }

                if (!alpha.isOnMap()) {   // It's day, and it is on the map, but the alpha wolf isn't on the map
                    move();
                }
            }
            else {  // It's day but it isn't on the map
                exitDen();
            }
        }
        else {  // It's night
            if (isOnMap()) {  // It's night and it is on the map
                tryEnterDen();
            }
            else {  // It's night and it isn't on the map

            }
        }
    }

    @Override
    protected void doEverySimulationStep() {}

    @Override
    public Carcass die() {
        Carcass carcass = super.die();

        if (wolfGang != null)
            wolfGang.flockMemberDied(this);

        return carcass;
    }

    /* ----- ----- ----- ----- Wolf Den ----- ----- ----- ----- */
    /**
     * @throws NullPointerException If actor isn't on the world map*/
    private void tryEnterDen() {
        if (wolfDen == null) return;

        if (PathFinder.distance(getLocation(), wolfGang.getShelterLocation()) < 2) {
            enterDen();
        }
        else {
            goToDen();
        }
    }

    private void goToDen() {
        Location moveToTile = PathFinder.getMoveToTile(world, getLocation(), wolfGang.getShelterLocation());
        if (moveToTile != null) world.move(this, moveToTile);
    }

    private void enterDen() {
        updateOnMap(new Location(0,0), false);
        wolfDen.wolfEnteredDen(this);
    }

    protected void exitDen() {
        if (isInfected()) System.out.println("s");

        TileFinder tileFinder = new TileFinder(world);
        Location spawnAt = tileFinder.getEmptyTileAroundActor(wolfDen, true);
        if (spawnAt == null) return;

        updateOnMap(spawnAt, true);
        wolfDen.wolfLeftDen(this);
    }

    /* ----- ----- ----- ----- Fighting ----- ----- ----- ----- */

    @Override
    protected boolean tryFight() {
        List<Predator> enemies = new ArrayList<>();
        if (!lookForEnemy(enemies, 1)) return false;

        Wolf enemy = null;
        for (Predator p : enemies) {
            if (p instanceof Wolf w) {
                enemy = w;
            }
        }
        if (enemy == null) return false;

        attackEnemy(enemy);
        return true;
    }

    @Override
    public double getStrengthValue() {
        int strength = 0;
        strength += strengthBonus_AnimalSize.get(animalSize);
        strength += strengthBonus_FungiState.get(fungiState);
        strength += strengthBonus_WolfType.get(wolfType);

        return strength;
    }

    /* ----- ----- ----- ----- NPC Wolf Specific ----- ----- ----- ----- */

    public void followAlpha(Location alphaLocation) {
        if (!isOnMap()) return;

        Location wolfLocation = getLocation();
        double distance = PathFinder.distance(wolfLocation, alphaLocation);


        if (distance >= wolfGang.getOptimalRadiusAroundAlpha()) { // if the wolf is within the allowed radius of the alpha
            Location moveToLocation = PathFinder.getMoveToTile(world, wolfLocation, alphaLocation);
            if (moveToLocation != null) world.move(this, moveToLocation);
        }
        if (animalSize.equals(CapableEnums.AnimalSize.ADULT)) {
            if (!(tryFight() || lookForFood(1)))
                move();
        }
        else {
            if (!lookForFood(2))
                move();
        }
    }

    /* ----- ----- ----- ----- Alpha Wolf Specific ----- ----- ----- ----- */

    private void digWolfDen() {
        Object nonBlocking = world.getNonBlocking(getLocation());
        if (nonBlocking != null) {
            if (nonBlocking instanceof AnimalShelter) return;
            else world.delete(nonBlocking);
        }

        wolfDen = new WolfDen(world, wolfGang);
        new SpawningAgent(world).spawnActorAtLocation(wolfDen, getLocation());

        wolfGang.flockShelterCreated(wolfDen);
    }

    private void promoteToAlpha() {
        wolfType = CapableEnums.WolfType.ALPHA;
    }


    // alpha can see whole map TODO and move to animals or something
    private void alphaSight() {
        // Gets references to all the possible food sources
        Map<String, Set<WorldActor>> allPossibleFoodActors = new WorldUtils(world).getAllWorldActorsAsMap(Animal.eatableFoodTypes.get(actorType));

        if (false) {    // Debug
            System.out.println(allPossibleFoodActors.size());
            for (String at : allPossibleFoodActors.keySet()) {
                System.out.println("Number of " + at + " in the world: " + allPossibleFoodActors.get(at).size());
            }
            System.out.println();
        }

        // Finds the closest one
        if (false) {
            double shortestDistance = Double.MAX_VALUE;
            WorldActor nearestFoodActor = null;

            // This is dumb because there is no priority in the food source
            for (String actorType : allPossibleFoodActors.keySet()) {
                for (WorldActor actor : allPossibleFoodActors.get(actorType)) {
                    double distance = PathFinder.distance(getLocation(), world.getLocation(actor));
                    if (distance < shortestDistance) {
                        shortestDistance = distance;
                        nearestFoodActor = actor;
                    }
                }
            }
        }


        // smart because it is categorised
        record PreyDist(WorldActor actor, double distance) {}   //

        Map<String, PreyDist> nearestPreyActors = new HashMap<>();
        Map<String, Double> distances = new HashMap<>();

        for (String actorType : allPossibleFoodActors.keySet()) {
            distances.put(actorType, Double.MAX_VALUE);
            for (WorldActor actor : allPossibleFoodActors.get(actorType)) {
                double distance = PathFinder.distance(getLocation(), world.getLocation(actor));
                if (distance < distances.get(actorType)) {
                    distances.put(actorType, distance);
                    nearestPreyActors.put(actorType, new PreyDist(actor, distance));
                }
            }
        }

        for (String at : Animal.eatableFoodTypes.get(actorType)) {

        }


    }


    /* ----- ----- ----- ----- Events ----- ----- ----- ----- */

    @Override
    public void onDawn() {
        animalState = CapableEnums.AnimalState.AWAKE;
        if (isInfected()) System.out.println("s");
        if (!isOnMap()) exitDen();
    }

    @Override
    public void onNightFall() {
        animalState = CapableEnums.AnimalState.SLEEPING;
        if (isOnMap()) tryEnterDen();
    }

    @Override
    public void onDusk() {
        if (wolfType.equals(CapableEnums.WolfType.ALPHA) && wolfDen == null) {
            digWolfDen();
        }
        if (wolfDen != null) {
            goToDen();
        }
    }

    /* ----- ----- ----- ----- Flock Animal Behavior ----- ----- ----- ----- */

    /** Updates the wolf's alpha. This is called from the Wolf's AnimalFlock.
     *
     * @param newLeader The new leader of the flock
     * @throws IllegalArgumentException when newLeader isn't an instance of Wolf
     */
    public void newFlockLeader(Animal newLeader) {
        if (newLeader instanceof Wolf wolf) {
            setAlpha(wolf);
        }
        else {
            throw new IllegalArgumentException("In (Wolf) newFlockLeader(): newLeader must be instance of Wolf");
        }
    }

    /** Sets the wolf's wolfDen. This is called from the Wolf's AnimalFlock.
     * @param shelter Is the reference to be set
     * @throws IllegalArgumentException If the shelter isn't an instance of WolfDen
     */
    public void setFlockShelter(AnimalShelter shelter) {
        if (shelter instanceof WolfDen den) {
            wolfDen = den;
        }
        else {
            throw new IllegalArgumentException("In (Wolf) setFlockDen(): shelter must be instance of WolfDen");
        }
    }

    /** Sets the wolf's wolfGang. This is called from the Wolf's AnimalFlock.
     * @param flock Is the reference to be set
     * @throws IllegalArgumentException If the shelter isn't an instance of WolfGang
     */
    public void setFlock(AnimalFlock flock) {
        if (flock instanceof WolfGang wolfGang) {
            this.wolfGang = wolfGang;
        }
        else {
            throw new IllegalArgumentException("In (Wolf) setFlock(): flock must be instance of WolfGang");
        }
    }

    public AnimalShelter getShelter() {
        return wolfGang.getShelter();
    }

    /* ----- ----- ----- ----- Getters ----- ----- ----- ----- */


    public WolfGang getWolfGang() {return wolfGang;}

    public boolean isAlpha() {return wolfType.equals(CapableEnums.WolfType.ALPHA);}

    @Override
    protected boolean isAnimalEnemy(Predator possibleEnemy) {
        if (possibleEnemy instanceof Wolf wolf) {
            if (wolfGang == null) return true;
            else
                return (!wolfGang.isMemberOfFlock(wolf));
        }
        else if (possibleEnemy instanceof Bear){
            List<Wolf> nearbyWolfsFromGang = new ArrayList<>();
            wolfGang.getNearbyWolfsFromGang(this, nearbyWolfsFromGang);

            return nearbyWolfsFromGang.size() >= 3;
        }
        return false;
    }

    @Override
    public DisplayInformation getInformation() {
        DisplayInformation returnValue = displayInformations.get(getDisplayInformationsKey());

        if (wolfType == CapableEnums.WolfType.ALPHA) {
            //returnValue = new DisplayInformation(Color.pink, animalState.equals(CapableEnums.AnimalState.AWAKE) ? "alpha-wolf" : "alpha-wolf-sleeping");
        }

        return returnValue;
    }

    @Override
    protected boolean getHasSpecialMovementBehaviour()  {return wolfType.equals(CapableEnums.WolfType.NPC);}


    /* ----- ----- ----- ----- Setters ----- ----- ----- ----- */

    public void setAlpha(Wolf wolf) {
        alpha = wolf;
        if(wolf == this) {
            promoteToAlpha();
        }
    }

    protected String getDisplayInformationsKey() {
        String key = animalSize.label + "-" + fungiState.label + "-" + animalState.label + "-" + wolfType.label;
        return key;
    }

    @Override
    public String getCombatLookupKey() {
        String key = animalSize.label + "-" + fungiState.label + "-" + wolfType.label;
        return key;
    }

}
