package CapableSimulator.Actors.Animals.Predators;

import CapableSimulator.Actors.Animals.Animal;
import CapableSimulator.Actors.Animals.AnimalFlock;
import CapableSimulator.Actors.Animals.FlockAnimal;
import CapableSimulator.Actors.Shelter.AnimalShelter;
import CapableSimulator.Actors.Shelter.WolfDen;
import CapableSimulator.Actors.WorldActor;
import CapableSimulator.CapableWorld;
import CapableSimulator.Utils.CapableEnums;
import CapableSimulator.Utils.SpawningAgent;
import CapableSimulator.Utils.TileFinder;
import CapableSimulator.Utils.WorldUtils;
import itumulator.executable.DisplayInformation;
import itumulator.world.Location;
import itumulator.world.World;

import java.awt.*;
import java.util.*;
import java.util.List;

public class Wolf extends Predator implements FlockAnimal {

    //the pack that the wolf is part of
    //Set<Actor> wolfGang;
    protected WolfGang wolfGang;

    protected Wolf alpha;
    protected WolfDen wolfDen;

    protected CapableEnums.WolfType wolfType;


    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        displayInformations.put("Small-Normal-Awake", new DisplayInformation(Color.pink, "wolf-small"));                   // The display information of a small awake normal wolf
        displayInformations.put("Big-Normal-Awake", new DisplayInformation(Color.magenta, "wolf"));                           // The display information of a big awake normal wolf

        displayInformations.put("Small-Normal-Sleeping", new DisplayInformation(Color.pink, "wolf-small-sleeping"));       // The display information of a small sleeping normal wolf
        displayInformations.put("Big-Normal-Sleeping", new DisplayInformation(Color.magenta, "wolf-sleeping"));               // The display information of a big sleeping normal wolf

        displayInformations.put("Small-Fungi-Awake", new DisplayInformation(Color.pink, "wolf-fungi-small"));              // The display information of a small awake fungus wolf
        displayInformations.put("Big-Fungi-Awake", new DisplayInformation(Color.magenta, "wolf-fungi"));                      // The display information of a big awake fungus wolf

        displayInformations.put("Small-Fungi-Sleeping", new DisplayInformation(Color.pink, "wolf-fungi-small-sleeping"));  // The display information of a small sleeping fungus wolf
        displayInformations.put("Big-Fungi-Sleeping", new DisplayInformation(Color.magenta, "wolf-fungi-sleeping"));          // The display information of a big sleeping fungus wolf
    }

    /* ----- ----- ----- ----- Constructors ----- ----- ----- ----- */

    //Default constructor for wolf, used in the actorConstructorRegistry
    public Wolf(CapableWorld world) {
        super("wolf",  world, 30, 0, 30);

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;

        wolfType = CapableEnums.WolfType.NPC;

        wolfGang = null;
    }

    public Wolf(CapableWorld world, int age, int MATING_AGE, int MATING_COOLDOWN_DURATION) {
        super("wolf", world, 30, age, 30, MATING_AGE, MATING_COOLDOWN_DURATION);

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;

        wolfType = CapableEnums.WolfType.NPC;
    }

    public Wolf(CapableWorld world, WolfGang wolfgang, Wolf alpha, WolfDen wolfDen, CapableEnums.AnimalSize animalSize, CapableEnums.AnimalState animalState, CapableEnums.FungiState fungiState) {
        super("wolf", world, 30, 0, 30);

        this.wolfGang = wolfgang;
        this.alpha = alpha;
        this.wolfDen = wolfDen;

        this.animalSize = animalSize;
        this.animalState = animalState;
        this.fungiState = fungiState;

        wolfType = CapableEnums.WolfType.NPC;
    }


    /* ----- ----- ----- ----- Behavior ----- ----- ----- ----- */

    //Act method implemented from Actor, every step the wolf is updated and methods are called.
    @Override
    public void act(World world){
        super.act(world);
        if (dead) return;

        if (world.isNight()) {
            if (isOnMap) tryEnterDen();
            else {

            }
        }
        else {
            //if (alpha == null) System.out.println(wolfType.toString());
            if (!isOnMap) {
                exitDen();
            }
            else {
                if (!alpha.isOnMap) {
                    move(world);
                }
            }
        }

        if (wolfType == CapableEnums.WolfType.ALPHA && world.isDay() && isOnMap) {
            lookForFood(1);
            wolfGang.alphaMoved(world.getLocation(this));
        }

    }

    @Override
    protected void attackEnemy(Predator enemyActor) {
        double winChance = 0.0;
        // Wolf
        if (enemyActor instanceof Wolf enemy) {
            winChance = getWinChance(enemy);

            if (new Random().nextDouble() < winChance) {
                kill(enemy);
            }
            else {
                becomeCarcass();
            }
        }
        // other enemy
    }

    /** Gets the win chance, dependent on the enemy */
    private double getWinChance(Wolf enemyWolf) {
        double winChance = 0.0;

        if (wolfType.equals(CapableEnums.WolfType.ALPHA)) {
            if (enemyWolf.isAlpha() && enemyWolf.isAnimalAdult()) winChance = 0.5;
            else if (enemyWolf.isAlpha() && !enemyWolf.isAnimalAdult()) winChance = 0.75;
            else if (!enemyWolf.isAlpha() && enemyWolf.isAnimalAdult()) winChance = 0.75;
            else winChance = 1;
        }
        else {
            if (enemyWolf.isAlpha() && enemyWolf.isAnimalAdult()) winChance = 0.0;
            else if (enemyWolf.isAlpha() && !enemyWolf.isAnimalAdult()) winChance = 0.5;
            else if (!enemyWolf.isAlpha() && enemyWolf.isAnimalAdult()) winChance = 0.5;
            else winChance = 0.75;
        }

        return winChance;
    }

    /**
     * @throws NullPointerException If actor isn't on the world map*/
    private void tryEnterDen() {
        if (wolfDen == null) return;

        if (distance(getLocation(), wolfGang.getShelterLocation()) <= 2) {
            enterDen();
        }
        else {
            goToDen();
        }
    }

    private void goToDen() {
        Location moveToTile = getMoveToTile(world, getLocation(), wolfGang.getShelterLocation());
        if (moveToTile != null) world.move(this, moveToTile);
    }

    private void enterDen() {
        updateOnMap(new Location(0,0), false);
        wolfDen.wolfEnteredDen(this);
    }

    protected void exitDen() {
        if (isOnMap) return;

        TileFinder tileFinder = new TileFinder(world);
        Location spawnAt = tileFinder.getEmptyTileAroundActor(wolfDen, true);
        if (spawnAt == null) return;

        updateOnMap(spawnAt, true);
        wolfDen.wolfLeftDen(this);
    }

    @Override
    public void die(World world) {
        System.out.println("Wolf Died");
        wolfGang.flockMemberDied(this); //wolfDied(this);
        world.delete(this);
        isOnMap = false;
    }


    /* ----- ----- ----- ----- NPC Wolf Specific ----- ----- ----- ----- */

    public void followAlpha(Location alphaLocation) {
        if (!isOnMap) return;

        Location wolfLocation = getLocation();
        double distance = Math.ceil(distance(wolfLocation, alphaLocation));


        if (distance >= wolfGang.getAllowedRadiusAroundAlpha()) { // if the wolf is within the allowed radius of the alpha
            Location moveToLocation = getMoveToTile(world, wolfLocation, alphaLocation);
            if (moveToLocation != null) world.move(this, moveToLocation);
        }
        if (animalSize.equals(CapableEnums.AnimalSize.ADULT))
            tryFight();
        else
            lookForFood(1);
    }

    private void tryFight() {
        System.out.println("Wolf Attacking");
        List<Predator> enemies = new ArrayList<>();
        if (lookForEnemy(enemies, 1)) {
            Wolf enemy = null;
            for (Predator p : enemies) {
                if (p instanceof Wolf w) {
                    enemy = w;
                }
            }
            if (enemy == null) return;

            System.out.println(this + " wolf is attacking");
            attackEnemy(enemy);
        }
        else lookForFood(1);
    }


    /* ----- ----- ----- ----- Alpha Wolf Specific ----- ----- ----- ----- */

    private void digWolfDen() {
        Object nonBlocking = world.getNonBlocking(getLocation());
        if (nonBlocking != null) {
            if (nonBlocking instanceof AnimalShelter) return;
            else world.delete(nonBlocking);
        }

        wolfDen = new WolfDen(world, wolfGang);
        new SpawningAgent(world).spawnActorAtLocation(wolfDen, getLocation());

        wolfGang.flockShelterCreated(wolfDen);
    }

    private void promoteToAlpha() {
        wolfType = CapableEnums.WolfType.ALPHA;
    }


    // alpha can see whole map TODO and move to animals or something
    private void alphaSight() {
        // Gets references to all the possible food sources
        Map<String, Set<WorldActor>> allPossibleFoodActors = new WorldUtils(world).getAllWorldActorsAsMap(Animal.eatableFoodTypes.get(actorType));

        if (false) {    // Debug
            System.out.println(allPossibleFoodActors.size());
            for (String at : allPossibleFoodActors.keySet()) {
                System.out.println("Number of " + at + " in the world: " + allPossibleFoodActors.get(at).size());
            }
            System.out.println();
        }

        // Finds the closest one
        if (false) {
            double shortestDistance = Double.MAX_VALUE;
            WorldActor nearestFoodActor = null;

            // This is dumb because there is no priority in the food source
            for (String actorType : allPossibleFoodActors.keySet()) {
                for (WorldActor actor : allPossibleFoodActors.get(actorType)) {
                    double distance = distance(getLocation(), world.getLocation(actor));
                    if (distance < shortestDistance) {
                        shortestDistance = distance;
                        nearestFoodActor = actor;
                    }
                }
            }
        }


        // smart because it is categorised
        record PreyDist(WorldActor actor, double distance) {}   //

        Map<String, PreyDist> nearestPreyActors = new HashMap<>();
        Map<String, Double> distances = new HashMap<>();

        for (String actorType : allPossibleFoodActors.keySet()) {
            distances.put(actorType, Double.MAX_VALUE);
            for (WorldActor actor : allPossibleFoodActors.get(actorType)) {
                double distance = distance(getLocation(), world.getLocation(actor));
                if (distance < distances.get(actorType)) {
                    distances.put(actorType, distance);
                    nearestPreyActors.put(actorType, new PreyDist(actor, distance));
                }
            }
        }

        for (String at : Animal.eatableFoodTypes.get(actorType)) {

        }


    }


    /* ----- ----- ----- ----- Events ----- ----- ----- ----- */

    @Override
    public void onDawn() {
        animalState = CapableEnums.AnimalState.AWAKE;
        if (!isOnMap) exitDen();
    }

    @Override
    public void onNightFall() {
        animalState = CapableEnums.AnimalState.SLEEPING;
        if (isOnMap) tryEnterDen();
    }

    @Override
    public void onDusk() {
        if (wolfType.equals(CapableEnums.WolfType.ALPHA) && wolfDen == null) {
            digWolfDen();
        }
        if (wolfDen != null) {
            goToDen();
        }
    }

    /* ----- ----- ----- ----- Flock Animal Behavior ----- ----- ----- ----- */

    /** Updates the wolf's alpha. This is called from the Wolf's AnimalFlock.
     *
     * @param newLeader The new leader of the flock
     * @throws IllegalArgumentException when newLeader isn't an instance of Wolf
     */
    public void newFlockLeader(Animal newLeader) {
        if (newLeader instanceof Wolf wolf) {
            setAlpha(wolf);
        }
        else {
            throw new IllegalArgumentException("In (Wolf) newFlockLeader(): newLeader must be instance of Wolf");
        }
    }

    /** Sets the wolf's wolfDen. This is called from the Wolf's AnimalFlock.
     * @param shelter Is the reference to be set
     * @throws IllegalArgumentException If the shelter isn't an instance of WolfDen
     */
    public void setFlockShelter(AnimalShelter shelter) {
        if (shelter instanceof WolfDen den) {
            wolfDen = den;
        }
        else {
            throw new IllegalArgumentException("In (Wolf) setFlockDen(): shelter must be instance of WolfDen");
        }
    }

    /** Sets the wolf's wolfGang. This is called from the Wolf's AnimalFlock.
     * @param flock Is the reference to be set
     * @throws IllegalArgumentException If the shelter isn't an instance of WolfGang
     */
    public void setFlock(AnimalFlock flock) {
        if (flock instanceof WolfGang wolfGang) {
            this.wolfGang = wolfGang;
        }
        else {
            throw new IllegalArgumentException("In (Wolf) setFlock(): flock must be instance of WolfGang");
        }
    }

    /* ----- ----- ----- ----- Getters ----- ----- ----- ----- */

    public WolfGang getWolfGang() {return wolfGang;}

    public boolean isAlpha() {return wolfType.equals(CapableEnums.WolfType.ALPHA);}

    @Override
    protected boolean isAnimalEnemy(Predator possibleEnemy) {
        if (possibleEnemy instanceof Wolf wolf) {
            return (wolfGang.isMemberOfFlock(wolf));
        }
        else if (possibleEnemy instanceof Bear){
            List<Wolf> nearbyWolfsFromGang = new ArrayList<>();
            wolfGang.getNearbyWolfsFromGang(this, nearbyWolfsFromGang);

            return nearbyWolfsFromGang.size() >= 3;
        }
        return false;
    }

    @Override
    public DisplayInformation getInformation() {
        DisplayInformation returnValue = displayInformations.get(getDisplayInformationsKey());

        if (wolfType == CapableEnums.WolfType.ALPHA) {
            returnValue = new DisplayInformation(Color.pink, animalState.equals(CapableEnums.AnimalState.AWAKE) ? "alpha-wolf" : "alpha-wolf-sleeping");
        }

        return returnValue;
    }

    @Override
    protected boolean getHasSpecialMovementBehaviour()  {return wolfType.equals(CapableEnums.WolfType.NPC);}


    /* ----- ----- ----- ----- Setters ----- ----- ----- ----- */

    public void setAlpha(Wolf wolf) {
        alpha = wolf;
        if(wolf == this) {
            promoteToAlpha();
        }
    }

}
