package CapableSimulator.Actors.Animals;

import CapableSimulator.Actors.Shelter.Burrow;
import CapableSimulator.CapableWorld;
import CapableSimulator.Utils.CapableEnums;
import CapableSimulator.Utils.SpawningAgent;
import CapableSimulator.Utils.TileFinder;
import itumulator.executable.DisplayInformation;
import itumulator.world.Location;
import itumulator.world.World;

import java.awt.*;
import java.util.*;
import java.util.List;

public class Rabbit extends Animal {

    /* ----- ----- ----- Burrow variables ----- ----- ----- */

    /** The reference to the rabbits burrow */
    private Burrow burrow;

    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        displayInformations.put("Small-Normal-Awake", new DisplayInformation(Color.red, "rabbit-small"));                   // The display information of a small awake normal rabbit
        displayInformations.put("Big-Normal-Awake", new DisplayInformation(Color.red, "rabbit"));                           // The display information of a big awake normal rabbit

        displayInformations.put("Small-Normal-Sleeping", new DisplayInformation(Color.red, "rabbit-small-sleeping"));       // The display information of a small sleeping normal rabbit
        displayInformations.put("Big-Normal-Sleeping", new DisplayInformation(Color.red, "rabbit-sleeping"));               // The display information of a big sleeping normal rabbit

        displayInformations.put("Small-Fungi-Awake", new DisplayInformation(Color.red, "rabbit-fungi-small"));              // The display information of a small awake fungus rabbit
        displayInformations.put("Big-Fungi-Awake", new DisplayInformation(Color.red, "rabbit-fungi"));                      // The display information of a big awake fungus rabbit

        displayInformations.put("Small-Fungi-Sleeping", new DisplayInformation(Color.red, "rabbit-fungi-small-sleeping"));  // The display information of a small sleeping fungus rabbit
        displayInformations.put("Big-Fungi-Sleeping", new DisplayInformation(Color.red, "rabbit-fungi-sleeping"));          // The display information of a big sleeping fungus rabbit
    }

    DisplayInformation diRabbit = new DisplayInformation(Color.red, "rabbit-large");


    /* ----- ----- ----- Constructors ----- ----- ----- */

    /**
     * The default constructor for the rabbit class.
     * This is the constructor to use when making the simulation.
     * */
    public Rabbit(CapableWorld world) {
        super("rabbit", world, 15, 0, 25);

        burrow = null;
        isOnMap = false;

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;
    }

    /**
     * A constructor where the rabbits starting energy can be defined, mostly for testing purposes.
     * */
    public Rabbit(CapableWorld world, int energy) {
        super("rabbit", world, energy, 0, 25);

        burrow = null;
        isOnMap = false;

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;
    }

    /**
     * A constructor where the age required before mating can occur and how long before mating can occur again can be defined.
     * */
    public Rabbit(CapableWorld world, int age, int MATING_AGE, int MATING_COOLDOWN_DURATION) {
        super("rabbit", world, 15, 25, age,  MATING_AGE, MATING_COOLDOWN_DURATION);

        burrow = null;
        isOnMap = false;

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;
    }

    /* ----- ----- ----- Behavior ----- ----- ----- */

    /** Implementation of act() method from the Actor interface.
     *  Executes once per simulation step.
     *  Most of the behavior occurs within this method.
     * */
    @Override
    public void act(World world) {
        if(world.isNight() || !isOnMap)
            return;
        findMate(1);



        lookForFood(2);

    }


    /** Tries to find a mate to reproduce
     *  If more than one possible mate is found, then a random one is chosen.
     *  If the chosen mate is eligible to reproduce, then a offspring is created.
     *  The offspring is inserted into the world at a free surrounding tile, around the instigating rabbit
     *  If no free tile is found the offspring dies, but the mating is still counted as a success. TODO
     *  // TODO when the mate is chosen, set a variable in the other mate to make sure that they dont try and mate with another rabbit in the same turn.
     * */
    public void findMate(int radius) {
        // If Rabbit can't reproduce, the do nothing
        if (!canMate())
            return;

        // Findes rabbits on surrounding tiles
        List<Rabbit> possibleMates = new ArrayList<>();
        for (Location l : world.getSurroundingTiles(getLocation(), radius)) {
            if (world.getTile(l) instanceof Rabbit rabbit)
                possibleMates.add(rabbit);
        }
        if (possibleMates.isEmpty()) return;

        // Select a mate
        Rabbit mate;
        if (possibleMates.size() == 1) {
            mate = possibleMates.get(0);
        }
        else {
            mate =  possibleMates.get(new Random().nextInt(possibleMates.size()));
        }

        // If mate can't mate, the do nothing
        if (!mate.canMate()) return;

        reproduce(mate);
    }

    protected void reproduce(Rabbit mate) {
        // If the distance between this rabbit and the mate is over 1 tile
        if (Math.ceil(distance(getLocation(), mate.getLocation())) > 1) {
            Location moveTo = getClosestTile(world, mate.getLocation());
            world.move(this,  moveTo);
        }

        // Findes empty location around this rabbit
        TileFinder tileFinder = new TileFinder(world);
        Location offspringLocation = tileFinder.getEmptyTileAroundActor(this, true);
        if (offspringLocation == null) return;

        // makes new rabbit
        Rabbit offspring = new Rabbit(world);

        // Spawn offspring at location
        SpawningAgent spawningAgent = new SpawningAgent(world);
        spawningAgent.spawnActorAtLocation(offspring,  offspringLocation);

        // Updates the relevant mating information.
        animalJustReproduce();
        mate.animalJustReproduce();
    }



    /** Handels the digging of a burrow, and connecting the rabbit to the burrow.
     * */
    public void digBurrow() {
        Object standingOn = world.getNonBlocking(world.getLocation(this));
        if (standingOn != null) {
            world.delete(standingOn);
        }

        burrow = new Burrow(world,this);
        new SpawningAgent(world).spawnActorAtLocation(burrow, getLocation());   // spawns the burrow on the map
        goIntoBurrow();
    }

    /** Handels entering the burrow */
    void goIntoBurrow() {
        updateOnMap(getLocation(), false);
        isOnMap = false;
    }

    /** Handles exiting the burrow */
    void exitBurrow() {
        if(burrow == null) System.out.println("Burrow is null");
        else {
            Location burrowLocation = world.getLocation(burrow);
            updateOnMap(burrowLocation, true);
            isOnMap = true;
        }
    }

    /* ----- ----- ----- ----- Events ----- ----- ----- ----- */

    /** The implementation of the animal method onDay()
     *  Handles the events linked to day break i.e.
     *  Enabling mating again, and the rabbit appearing on the map again.
     * */
    @Override
    public void onDawn() {
        animalState = CapableEnums.AnimalState.AWAKE;

        if(burrow == null) {
            System.out.println("Burrow is null");
            return;
        }

        if (!isOnMap)
            exitBurrow();
    }

    /** The implementation of the animal method onNight()
     *  Handles the events linked to nightfall i.e.
     *  The rabbit going into it's burrow if it has one, otherwise it tries to find a nearby burrow.
     *  If no nearby burrow is found, then it tries to dig one.
     * */
    @Override
    public void onNightFall() {
        animalState = CapableEnums.AnimalState.SLEEPING;

        if (burrow == null) {
            for (Location l : world.getSurroundingTiles(getLocation())) {
                if (world.getNonBlocking(l) instanceof Burrow burrow) {
                    this.burrow = burrow;
                    break;
                }
            }
            if (burrow == null) digBurrow();
        }
        goIntoBurrow();
    }

    /** The implementation of the animal method almostNight()
     *  Handles the events linked to it almost being night i.e.
     *  Making the rabbits go towards their burrow if they have one.
     *  Disabling mating until daybreak.
     * */
    @Override
    public void onDusk() {
        if(burrow == null) return;  // If rabbit doesn't have a burrow, then do nothing

        Location closestTile = getClosestTile(world, world.getLocation(burrow));
        if (closestTile == null) {
            System.out.println("Rabbit could not find a free tile around it's burrow.");    // error message if no empty tile was found around its burrow
            //TODO kill rabbit if no tile was found, burrow might be full
            return;
        }

        world.move(this, closestTile);
    }


    /* ----- ----- ----- ----- Getters ----- ----- ----- ----- ----- */

    /** Returns the rabbits burrow reference */
    public Burrow getBurrow() { return burrow; }

    @Override
    public DisplayInformation getInformation() {
        return diRabbit;
    }

}
