package CapableSimulator.Actors;

import CapableSimulator.Utils.CapableEnums;
import itumulator.executable.DisplayInformation;
import itumulator.world.Location;
import itumulator.world.World;

import java.awt.*;
import java.util.*;
import java.util.List;

public class Bear extends Predator {

    /** The center location of the bear's territory.
     *  The bear will only move around within the territory, except if it findes food just outside its territory.
     * */
    Location territoryCenter;

    /** The size of the bear's territory, given as a radius from the center location.
     * */
    int territoryRadius;




    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        displayInformations.put("Small-Normal-Awake", new DisplayInformation(Color.BLACK, "bear-small"));                   // The display information of a small awake normal bear
        displayInformations.put("Big-Normal-Awake", new DisplayInformation(Color.BLACK, "bear"));                           // The display information of a big awake normal bear

        displayInformations.put("Small-Normal-Sleeping", new DisplayInformation(Color.BLACK, "bear-small-sleeping"));       // The display information of a small sleeping normal bear
        displayInformations.put("Big-Normal-Sleeping", new DisplayInformation(Color.BLACK, "bear-sleeping"));               // The display information of a big sleeping normal bear

        displayInformations.put("Small-Fungi-Awake", new DisplayInformation(Color.BLACK, "bear-fungi-small"));              // The display information of a small awake fungus bear
        displayInformations.put("Big-Fungi-Awake", new DisplayInformation(Color.BLACK, "bear-fungi"));                      // The display information of a big awake fungus bear

        displayInformations.put("Small-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "bear-fungi-small-sleeping"));  // The display information of a small sleeping fungus bear
        displayInformations.put("Big-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "bear-fungi-sleeping"));          // The display information of a big sleeping fungus bear
    }


    /* ----- ----- ----- ----- Constructors ----- ----- ----- ----- */

    public Bear() {
        super("bear");
        this.territoryCenter = new Location(0, 0);
        this.territoryRadius = 6;
        this.energy = 20;
        this.maxEnergy = 30;

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.FUNGI;
    }

    public Bear(Location territoryCenter) {
        super("bear");
        this.territoryCenter = territoryCenter;
        this.territoryRadius = 1;

        this.energy = 3;
        this.maxEnergy = 30;

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.FUNGI;
    }

    /* ----- ----- ----- ----- Behavior ----- ----- ----- ----- */

    @Override
    public void act(World world) {
        super.act(world);
        if (!dead){
            lookForFood(2);
        }
        else {
            System.out.println("Dead, energy = " + energy);
        }
    }

    @Override
    public void move(World world){
        Set<Location> territory = world.getSurroundingTiles(territoryCenter, territoryRadius);
        Location[] neighbours = getPossibleFoodTiles(2);
        List<Location> validNeighbours = new ArrayList<>();
        for (Location neighbour : neighbours) {
            if (territory.contains(neighbour) && world.isTileEmpty(neighbour)) validNeighbours.add(neighbour);
        }
        Location searchLocation;
        if (validNeighbours.isEmpty()) {
            Location nearestLocation = getClosestTile(world,territoryCenter);
            if (nearestLocation == null) return;
            searchLocation =  nearestLocation;
        }
        else {
            Random rand = new Random();
            searchLocation = validNeighbours.get(rand.nextInt(validNeighbours.size()));
        }
        world.move(this, searchLocation);
    }
    // TODO make test that test if a bear moves out of it territory.

    /* ----- ----- ----- ----- Fighting ----- ----- ----- ----- */

    @Override
    protected boolean isAnimalEnemy(Predator possibleEnemy) {
        if (possibleEnemy instanceof Wolf wolf) {
            List<Wolf> nearbyWolfs = new ArrayList<>();
            wolf.getWolfGang().getNearbyWolfsFromGang(wolf,  nearbyWolfs);
            return nearbyWolfs.size() < 3;
        }
        else if (possibleEnemy instanceof Bear){
            return (age > matingAge && matingCooldown <= 0);
        }
        return false;
    }

    /* ----- ----- ----- ----- Events ----- ----- ----- ----- */

    @Override
    public void onDay(World world) {}

    @Override
    public void onNight(World world) {}

    @Override
    public void almostNight(World world) {}

    /* ----- ----- ----- ----- Getters and Setters ----- ----- ----- ----- */

    @Override
    public DisplayInformation getInformation() {

        DisplayInformation returnValue = displayInformations.get(getDisplayInformationsKey());

        return returnValue;
    }
}
