package CapableSimulator.Actors;

import itumulator.executable.DisplayInformation;
import itumulator.world.World;
import itumulator.world.Location;

import java.awt.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


public class Putin extends Animals {

    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        // TODO Fix all the different possible Putin dispay informations
        displayInformations.put("Small-Normal-Awake", new DisplayInformation(Color.BLACK, "wolf-small"));                   // The display information of a small awake normal putin
        displayInformations.put("Big-Normal-Awake", new DisplayInformation(Color.BLACK, "wolf"));                           // The display information of a big awake normal putin

        displayInformations.put("Small-Normal-Sleeping", new DisplayInformation(Color.BLACK, "wolf-small-sleeping"));       // The display information of a small sleeping normal putin
        displayInformations.put("Big-Normal-Sleeping", new DisplayInformation(Color.BLACK, "wolf-sleeping"));               // The display information of a big sleeping normal putin

        displayInformations.put("Small-Fungi-Awake", new DisplayInformation(Color.BLACK, "wolf-fungi-small"));              // The display information of a small awake fungus putin
        displayInformations.put("Big-Fungi-Awake", new DisplayInformation(Color.BLACK, "wolf-fungi"));                      // The display information of a big awake fungus putin

        displayInformations.put("Small-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "wolf-fungi-small-sleeping"));  // The display information of a small sleeping fungus putin
        displayInformations.put("Big-Fungi-Sleeping", new DisplayInformation(Color.BLACK, "wolf-fungi-sleeping"));          // The display information of a big sleeping fungus putin
    }

    DisplayInformation diPutin = new DisplayInformation(Color.blue, "putin");

    public Putin(){
        super("putin");
        this.energy = 100;
        this.maxEnergy = 1000;
        this.age = 73;
    }


    /* ----- ----- ----- ----- Behavior ----- ----- ----- ----- */

    @Override
    public void act(World world){
        lookForFood(5);
    }


    /* ----- ----- ----- ----- Events ----- ----- ----- ----- */

    @Override
    public void onDay(World world){

    }

    @Override
    public void onNight(World world){

    }

    @Override
    public void almostNight(World world) {

    }


    /* ----- ----- ----- Getters and Setters ----- ----- ----- */

    @Override
    public DisplayInformation getInformation() { return diPutin; }

}

