package CapableSimulator.Actors;

import CapableSimulator.Utils.CapableEnums;
import CapableSimulator.Utils.SpawningAgent;
import CapableSimulator.Utils.TileFinder;
import CapableSimulator.Utils.WorldUtils;
import itumulator.executable.DisplayInformation;
import itumulator.simulator.Actor;
import itumulator.world.Location;
import itumulator.world.World;

import java.awt.*;
import java.util.*;
import java.util.List;

public class Wolf extends Predator {

    //the pack that the wolf is part of
    //Set<Actor> wolfGang;
    protected WolfGang wolfGang;

    protected Wolf alpha;
    protected WolfDen wolfDen;

    protected CapableEnums.WolfType wolfType;


    /** Defines the map wherein all the display information's are declared. The key is generated by the getDisplayInformationsKey() method */
    protected static final Map<String, DisplayInformation> displayInformations = new HashMap<>();
    static {
        displayInformations.put("Small-Normal-Awake", new DisplayInformation(Color.pink, "wolf-small"));                   // The display information of a small awake normal wolf
        displayInformations.put("Big-Normal-Awake", new DisplayInformation(Color.magenta, "wolf"));                           // The display information of a big awake normal wolf

        displayInformations.put("Small-Normal-Sleeping", new DisplayInformation(Color.pink, "wolf-small-sleeping"));       // The display information of a small sleeping normal wolf
        displayInformations.put("Big-Normal-Sleeping", new DisplayInformation(Color.magenta, "wolf-sleeping"));               // The display information of a big sleeping normal wolf

        displayInformations.put("Small-Fungi-Awake", new DisplayInformation(Color.pink, "wolf-fungi-small"));              // The display information of a small awake fungus wolf
        displayInformations.put("Big-Fungi-Awake", new DisplayInformation(Color.magenta, "wolf-fungi"));                      // The display information of a big awake fungus wolf

        displayInformations.put("Small-Fungi-Sleeping", new DisplayInformation(Color.pink, "wolf-fungi-small-sleeping"));  // The display information of a small sleeping fungus wolf
        displayInformations.put("Big-Fungi-Sleeping", new DisplayInformation(Color.magenta, "wolf-fungi-sleeping"));          // The display information of a big sleeping fungus wolf
    }

    //Default constructor for wolf, used in the actorConstructorRegistry
    public Wolf() {
        super("wolf");
        this.energy = 20;
        this.maxEnergy = 30;
        this.age = 0;

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;
        wolfType = CapableEnums.WolfType.NPC;

        //actorType = "wolf";
    }

    //Wolf constructor used for instantiating new wolves, with a pack as parameter.
    public Wolf(Set<Actor> wolfgang) {
        super("wolf");
        this.energy = 20;
        this.maxEnergy = 30;
        this.age = 0;
        //this.wolfGang = wolfgang;

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;
        wolfType = CapableEnums.WolfType.NPC;
    }

    public Wolf(WolfGang wolfgang, boolean isAlpha) {
        super("wolf");
        //this.energy = isAlpha ? 20 : 100;
        this.energy = 20;
        this.maxEnergy = 30;
        this.age = 0;
        this.wolfGang = wolfgang;

        animalSize = CapableEnums.AnimalSize.BABY;
        animalState = CapableEnums.AnimalState.AWAKE;
        fungiState = CapableEnums.FungiState.NORMAL;
        wolfType = isAlpha ? CapableEnums.WolfType.ALPHA : CapableEnums.WolfType.NPC;

        hasSpecialMovementBehaviour = wolfType.equals(CapableEnums.WolfType.NPC);
    }

    public Wolf(WolfGang wolfgang, Wolf alpha, WolfDen wolfDen, CapableEnums.AnimalSize animalSize, CapableEnums.AnimalState animalState) {
        super("wolf");
        this.energy = 20;
        this.maxEnergy = 30;
        this.age = 0;

        this.wolfGang = wolfgang;
        this.alpha = alpha;
        this.wolfDen = wolfDen;

        this.animalSize = animalSize;
        this.animalState = animalState;
        fungiState = CapableEnums.FungiState.NORMAL;
        wolfType = CapableEnums.WolfType.NPC;

        hasSpecialMovementBehaviour = true;
    }

    //Act method implemented from Actor, every step the wolf is updated and methods are called.
    @Override
    public void act(World world){
        if (dead) return;

        if (world.isNight()) {
            if (isOnMap) goIntoDen(world);
            else {

            }
        }
        else {
            //if (alpha == null) System.out.println(wolfType.toString());
            if (!isOnMap) {
                exitDen(world);
            }
            else {
                if (!alpha.isOnMap) {
                    lookForFood(1);
                }
            }
        }

        if (wolfType == CapableEnums.WolfType.ALPHA && world.isDay() && isOnMap) {
            lookForFood(1);
            wolfGang.alphaMoved(world, world.getLocation(this));


        }
        //doEverySimStep(world);

        //lookForFood(world, 2);


    }

    private void doEverySimStep(World world){
        energy--;
        if(energy <= 0) this.die(world);
        age++;
        if (animalSize == CapableEnums.AnimalSize.BABY && age > 10) animalSize = CapableEnums.AnimalSize.ADULT;
    }

    // alpha can see whole map TODO
    private void alphaSight(World world) {
        // Gets references to all the possible food sources
        Map<String, Set<WorldActor>> allPossibleFoodActors = new WorldUtils(world).getAllWorldActorsAsMap(eatableFoodTypes.get(actorType));

        if (false) {    // Debug
            System.out.println(allPossibleFoodActors.size());
            for (String at : allPossibleFoodActors.keySet()) {
                System.out.println("Number of " + at + " in the world: " + allPossibleFoodActors.get(at).size());
            }
            System.out.println();
        }

        // Finds the closest one
        if (false) {
            double shortestDistance = Double.MAX_VALUE;
            WorldActor nearestFoodActor = null;

            // This is dumb because there is no priority in the food source
            for (String actorType : allPossibleFoodActors.keySet()) {
                for (WorldActor actor : allPossibleFoodActors.get(actorType)) {
                    double distance = distance(getLocation(), world.getLocation(actor));
                    if (distance < shortestDistance) {
                        shortestDistance = distance;
                        nearestFoodActor = actor;
                    }
                }
            }
        }


        // smart because it is categorised
        record PreyDist(WorldActor actor, double distance) {}   //

        Map<String, PreyDist> nearestPreyActors = new HashMap<>();
        Map<String, Double> distances = new HashMap<>();

        for (String actorType : allPossibleFoodActors.keySet()) {
            distances.put(actorType, Double.MAX_VALUE);
            for (WorldActor actor : allPossibleFoodActors.get(actorType)) {
                double distance = distance(getLocation(), world.getLocation(actor));
                if (distance < distances.get(actorType)) {
                    distances.put(actorType, distance);
                    nearestPreyActors.put(actorType, new PreyDist(actor, distance));
                }
            }
        }

        for (String at : eatableFoodTypes.get(actorType)) {

        }


    }

    public void followAlpha(World world, Location alphaLocation) {
        if (!isOnMap || dead) return;

        Location wolfLocation = getLocation();
        double distance =distance(wolfLocation, alphaLocation);


        if (distance >= wolfGang.radiusAroundAlpha) { // if the wolf is within the allowed radius of the alpha
            //something
        }

        Location moveToLocation = getMoveToTile(world, wolfLocation, alphaLocation);
        if (moveToLocation != null) world.move(this, moveToLocation);
        else move(world);
        List<Predator> enemies = new ArrayList<>();
        if (lookForEnemy(enemies, 1)) {
            Wolf enemy = null;
            for (Predator p : enemies) {
                if (p instanceof Wolf w) {
                    enemy = w;
                }
            }
            if (enemy == null) return;

            System.out.println(this + " wolf is attacking");
            attackEnemy(world, enemy);
        }
        else lookForFood(1);
    }


    protected void attackEnemy(World world, Wolf enemy) {
        double winChance = 0.0;
        if (animalSize.equals(CapableEnums.AnimalSize.ADULT)) {

            if (wolfType.equals(CapableEnums.WolfType.ALPHA)) {
                if (enemy.isAlpha() && enemy.isAnimalAdult()) winChance = 0.5;
                else if (enemy.isAlpha() && !enemy.isAnimalAdult()) winChance = 0.75;
                else if (!enemy.isAlpha() && enemy.isAnimalAdult()) winChance = 0.75;
                else winChance = 1;
            }
            else {
                if (enemy.isAlpha() && enemy.isAnimalAdult()) winChance = 0.0;
                else if (enemy.isAlpha() && !enemy.isAnimalAdult()) winChance = 0.5;
                else if (!enemy.isAlpha() && enemy.isAnimalAdult()) winChance = 0.5;
                else winChance = 0.75;
            }

        }
        else return;

        if (new Random().nextDouble() < winChance) {
            kill(enemy);
        }
        else {
            becomeCarcass(world);
        }
    }


    public void setAlpha(Wolf wolf) {
        this.alpha = wolf;
        hasSpecialMovementBehaviour = false;
    }

    public void promoteToAlpha() {
        wolfType = CapableEnums.WolfType.ALPHA;
        wolfGang.setNewAlpha(this);
        setAlpha(alpha);
    }


    private void digWolfDen(World world) {
        Object nonBlocking = world.getNonBlocking(getLocation());
        if (nonBlocking != null) {
            if (nonBlocking instanceof Burrow || nonBlocking instanceof WolfDen) return;
            else world.delete(nonBlocking);
        }
        wolfDen = new WolfDen(wolfGang);
        new SpawningAgent(world).spawnActorAtLocation(wolfDen, getLocation());
        wolfGang.wolfDenCreated(world, wolfDen);
    }


    public void setWolfDen(WolfDen wolfDen) {
        if (wolfDen == null) {
            throw new NullPointerException("In SetWolfDen(): WolfDen is null");
        }
        if (this.wolfDen != null) {
            System.out.println("setWolfDen(): WolfDen is already set");
            return;
        }
        this.wolfDen = wolfDen;
    }

    protected void goIntoDen(World world) {
        if (wolfGang.denLocation == null) return;
        Location wolfLocation = getLocation();

        if (distance(wolfLocation, wolfGang.denLocation) <= 2 && isOnMap) {
            updateOnMap(world, wolfLocation, false);
            wolfDen.wolfEnteredDen(this);
        }
        else {
            Location moveToTile = getMoveToTile(world, wolfLocation, wolfGang.denLocation);
            if (moveToTile != null) world.move(this, moveToTile);
        }

        //if (isOnMap && world.getCurrentTime() == 19) System.out.println(distance(wolfLocation, wolfGang.denLocation));
    }

    protected void exitDen(World world) {
        if (wolfGang == null && wolfGang.denLocation == null) return;

        TileFinder tileFinder = new TileFinder(world);
        Location spawnAt = tileFinder.getEmptyTileAroundActor(wolfDen, true);
        if (spawnAt == null) return;

        updateOnMap(world, spawnAt, true);
        wolfDen.wolfLeftDen(this);
    }

    @Override
    public void die(World world) {
        wolfGang.wolfDied(this);
        world.delete(this);
        dead = true;
    }

    @Override
    public void onDay(World world) {
        animalState = CapableEnums.AnimalState.AWAKE;
        if (!isOnMap) exitDen(world);
    }

    @Override
    public void onNight(World world) {
        animalState = CapableEnums.AnimalState.SLEEPING;
    }

    @Override
    public void almostNight(World world) {
        if (wolfType.equals(CapableEnums.WolfType.ALPHA) && wolfDen == null) {
            digWolfDen(world);
        }
        if (wolfDen != null) {
            //System.out.println("go to den");
        }
    }

    public WolfGang getWolfGang() {return wolfGang;}

    public boolean isAlpha() {return wolfType.equals(CapableEnums.WolfType.ALPHA);}

    @Override
    public DisplayInformation getInformation() {
        DisplayInformation returnValue = displayInformations.get(getDisplayInformationsKey());

        if (wolfType == CapableEnums.WolfType.ALPHA) {
            returnValue = new DisplayInformation(Color.pink, animalState.equals(CapableEnums.AnimalState.AWAKE) ? "alpha-wolf" : "alpha-wolf-sleeping");
        }

        return returnValue;
    }

    @Override
    protected boolean isAnimalEnemy(Predator possibleEnemy) {
        if (possibleEnemy instanceof Wolf wolf) {
            return (wolf.getWolfGang() != this.wolfGang);
        }
        else if (possibleEnemy instanceof Bear){
            List<Wolf> nearbyWolfsFromGang = new ArrayList<>();
            wolfGang.getNearbyWolfsFromGang(this, nearbyWolfsFromGang);

            return nearbyWolfsFromGang.size() >= 3;
        }
        return false;
    }

}
